redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: &redis

production: 
  adapter: redis
  url: redis://h:pdd57ec24c4d81aaa240be97d3f6bf8b19b3b675bfa10b0dd7416e4a4a1de4ead@ec2-34-206-56-30.compute-1.amazonaws.com:55689

test:
  adapter: async